### PR TITLE
Update contributors.md

### PR DESCRIPTION
**Pull request by 94Akriti**

### CODE REVIEW

**Comment by Harshalshree** [comment]
Hi Akriti, please add your code in the contributions folder as well.

**Comment by 94Akriti** [comment]
> Hi Akriti, please add your code in the contributions folder.

in main of DSC?

**Comment by 94Akriti** [comment]
> Hi Akriti, please add your code in the contributions folder.

I'm unable to add this code file to dscvitc main > contributions folder.But I have added my name and bio in the .md text file
Please add by yourself .

**Comment by 94Akriti** [comment]
> Hi Akriti, please add your code in the contributions folder.

I Have created a pull request

**Pull request closed without merging**
